spring.application.name=${SPRING_APPLICATION_NAME: springsecuritysection3}

# Instead of using below hardcoded using InMemoryUserDetailsManager in the SecurityConfiguration.java file
#spring.security.user.name=${SECURITY_NAME:abc}
#spring.security.user.password=${SECURITY_PASSWORD:12345}