spring.application.name=${SPRING_APP_NAME:springsecuritysection1}

message = Hey welcome to spring with security!


spring.security.user.name=${SECURITY_NAME:abc}
spring.security.user.password=${SECURITY_PASSWORD:12345}